import os
from dotenv import load_dotenv
load_dotenv()

#LEADER-M
LEADER_M_FEED = os.getenv('LEADER_M_FEED')

#LEADER
LEADER_FEED = os.getenv('LEADER_FEED')

#COMPUWORLD
CW_FEED = os.getenv('CW_FEED')

#BLUECHIP
BL_FEED = os.getenv('BL_FEED')

#MULTIMEDIA
MMT_FEED = os.getenv('MMT_FEED')

#MITTONI
MITTONI_USERNAME = os.getenv('MITTONI_USERNAME')
MITTONI_PASSWORD = os.getenv('MITTONI_PASSWORD')

#POWERHOUSEPC
PHPC_FEED = os.getenv('PHPC_FEED')

#IJK
IJK_USERNAME = os.getenv('IJK_USERNAME')
IJK_PASSWORD = os.getenv('IJK_PASSWORD')

#FORCE TECHNOLOGY
FORCE_USERNAME = os.getenv('FORCE_USERNAME')
FORCE_PASSWORD = os.getenv('FORCE_PASSWORD')

#4CABLING
FEED_4CABLING = os.getenv('FEED_4CABLING')

#ALLOY
ALLOY_FEED = os.getenv('ALLOY_FEED')

#ALLOYS
ALLOYS_FEED = os.getenv('ALLOYS_FEED')

#DICKER DATA
DICKER_FEED = os.getenv('DICKER_FEED')

#AUSCOMP
AUSCOMP_FEED = os.getenv('AUSCOMP_FEED')
AUSCOMP_PORT = os.getenv('AUSCOMP_PORT')
AUSCOMP_FILENAME = os.getenv('AUSCOMP_FILENAME')
AUSCOMP_USERNAME = os.getenv('AUSCOMP_USERNAME')
AUSCOMP_PASSWORD = os.getenv('AUSCOMP_PASSWORD')

#NEWMAGIC
NEWMAGIC_USERNAME = os.getenv('NEWMAGIC_USERNAME')
NEWMAGIC_PASSWORD = os.getenv('NEWMAGIC_PASSWORD')

#STREAKWAVE
STREAKWAVE_FEED = os.getenv('STREAKWAVE_FEED')

#BCM LOGIN
BCM_USERNAME = os.getenv('BCM_USERNAME')
BCM_PASSWORD = os.getenv('BCM_PASSWORD')

#EMAIL LOGIN
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_USERNAME = os.getenv('EMAIL_USERNAME')
EMAIL_PASSWORD = os.getenv('EMAIL_PASSWORD')